### ISSUE TITLE
Invalid header size

### ISSUE THREAD

**Issue by MadEwink** [MadEwink/numamma#2]
It seems that while running, sometimes we encounter a "Invalid header size" problem. 49b93884315f2e08b308a16113f7f6b62d0fbcb4 was supposed to fix it, but I faced it once after applying it. Even if it seems realy rare, I want to investigate this a bit.
Log of the time it happened :

```
$ SAMPLING_RATE=1000 mem_intercept ~/home/mad/stage/NPB3.3.1/NPB3.3-OMP/bin/bt.A.x

NumaMMA settings:
-----------------
Sampling rate: 1000
Match samples: 1
Buffer size: 131072
Alarm interval: 0 ms
Memory access analysis: offline
-----------------
[NumaMMA]  This program was compiled with -fPIE. It is mapped at address 0x5645ed066000
Found a global variable: completed.7325 (defined at ). base addr=0x5645ed079100, size=1
Found a global variable: constants_ (defined at ). base addr=0x5645ed079120, size=1272
Found a global variable: fields_ (defined at ). base addr=0x5645ed079640, size=45427200
Found a global variable: global_ (defined at ). base addr=0x5645ed079620, size=24
Found a global variable: sec.2316 (defined at ). base addr=0x5645ed0790e8, size=4
Found a global variable: tt_ (defined at ). base addr=0x5645ed077660, size=1024
Found a global variable: work_1d_ (defined at ). base addr=0x5645ed066000, size=6240
Found a global variable: work_lhs_ (defined at ). base addr=0x5645ed067860, size=65024


 NAS Parallel Benchmarks (NPB3.3-OMP) - BT Benchmark

 No input file inputbt.data. Using compiled defaults
 Size:   64x  64x  64
 Iterations:  200       dt:   0.0008000
 Number of available threads:     4

 Time step    1
 Time step   20
 Time step   40
 Time step   60
 Time step   80
Error: invalid header size = 0

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fb3440f5b90 in ???
#1  0x7fb3440f4dc5 in ???
#2  0x7fb343d0b83f in ???
        at /build/glibc-vjB4T1/glibc-2.28/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x7fb343d0b7bb in __GI_raise
        at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x7fb343cf6534 in __GI_abort
        at /build/glibc-vjB4T1/glibc-2.28/stdlib/abort.c:79
#5  0x7fb344391b77 in __analyze_buffer
        at /home/mad/stage/numamma-build/numamma/src/mem_sampling.c:723
#6  0x7fb3443901ec in __copy_samples_thread
        at /home/mad/stage/numamma-build/numamma/src/mem_sampling.c:590
#7  0x7fb34438cf10 in numap_generic_handler
        at /home/mad/stage/numamma-build/numamma/src/mem_sampling.c:218
#8  0x7fb34438cf38 in numap_read_handler
        at /home/mad/stage/numamma-build/numamma/src/mem_sampling.c:222
#9  0x7fb343cc09c4 in ???
#10  0x7fb343ea772f in ???
        at /build/glibc-vjB4T1/glibc-2.28/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#11  0x5645ed070e4c in binvcrhs_
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/solve_subs.f:230
#12  0x5645ed070020 in y_solve_._omp_fn.0
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/y_solve.f:351
#13  0x7fb343f2ca41 in ???
#14  0x5645ed070238 in y_solve_
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/y_solve.f:45
#15  0x5645ed06b577 in adi_
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/adi.f:13
#16  0x5645ed067b00 in bt
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/bt.f:157
#17  0x5645ed068214 in main
        at /home/mad/stage/NPB3.3.1/NPB3.3-OMP/BT/bt.f:213
../../numamma-build/numamma/build/src/mem_intercept: line 76: 22487 Aborted                 LD_PRELOAD=$ld_preload LD_LIBRARY_PATH=$ld_library_path $prog_name $*
```

**Comment by MadEwink** [comment]
After running many many more tests for https://github.com/MadEwink/numamma/issues/3 this never happened again, let's say I did not recompile that time.
